Posteriormente, na fase de Transform, os dados são tratados, normalizados e enriquecidos através da criação de métricas derivadas relevantes para a análise de performance. Após estas transformações, os dados são armazenados numa camada intermédia de dados processados antes do seu carregamento para a base de dados.

# Transform

In [1]:
# import das bibliotecas necessárias
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
# ler os dados
competitions = pd.read_parquet("../data/raw/competitions.parquet")
events = pd.read_parquet("../data/raw/events.parquet")
lineups = pd.read_parquet("../data/raw/lineups.parquet")
matches = pd.read_parquet("../data/raw/matches.parquet")

In [3]:
pd.set_option("display.max_columns", None)

In [4]:
events

,50_50,bad_behaviour_card,ball_receipt_outcome,ball_recovery_recovery_failure,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_other,clearance_right_foot,counterpress,dribble_nutmeg,dribble_outcome,duel_outcome,duel_type,duration,foul_committed_advantage,foul_committed_card,foul_committed_offensive,foul_committed_type,foul_won_advantage,foul_won_defensive,goalkeeper_body_part,goalkeeper_end_location,goalkeeper_outcome,goalkeeper_position,goalkeeper_technique,goalkeeper_type,id,index,injury_stoppage_in_chain,interception_outcome,location_x,match_id,minute,off_camera,out,pass_aerial_won,pass_angle,pass_assisted_shot_id,pass_body_part,pass_cross,pass_cut_back,pass_end_location,pass_goal_assist,pass_height,pass_inswinging,pass_length,pass_miscommunication,pass_no_touch,pass_outcome,pass_outswinging,pass_recipient,pass_recipient_id,pass_shot_assist,pass_straight,pass_switch,pass_technique,pass_through_ball,pass_type,period,play_pattern,player,player_id,position,possession,possession_team,possession_team_id,related_events,second,shot_aerial_won,shot_body_part,shot_end_location,shot_first_time,shot_freeze_frame,shot_key_pass_id,shot_outcome,shot_statsbomb_xg,shot_technique,shot_type,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,tactics,team,team_id,timestamp,type,under_pressure,ball_recovery_offensive,block_deflection,dribble_no_touch,dribble_overrun,miscontrol_aerial_won,shot_deflected,shot_one_on_one,goalkeeper_shot_saved_to_post,shot_saved_to_post,block_offensive,goalkeeper_shot_saved_off_target,shot_saved_off_target,foul_committed_penalty,foul_won_penalty,pass_deflected,shot_redirect,goalkeeper_punched_out,shot_open_goal,block_save_block,goalkeeper_success_in_play,goalkeeper_penalty_saved_to_post,shot_follows_dribble,visible_area,teammate,actor,keeper,location_y
0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,9d27853c-ffbc-4011-b7eb-fe3d438e8376,1,None,None,None,3930166,0,None,None,None,NaN,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,NaN,None,None,None,None,None,None,1,Regular Play,None,NaN,None,1,Portugal,780,None,0,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,NaN,"{'formation': 3412.0, 'lineup': [{'jersey_numb...",Portugal,780,00:00:00.000,Starting XI,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,39ad76b2-caaa-41e0-8eb5-f42de9e4e2c6,2,None,None,None,3930166,0,None,None,None,NaN,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,NaN,None,None,None,None,None,None,1,Regular Play,None,NaN,None,1,Portugal,780,None,0,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,NaN,"{'formation': 352.0, 'lineup': [{'jersey_numbe...",Czech Republic,912,00:00:00.000,Starting XI,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,4785617c-2983-4911-a9a6-9edd69fd948b,3,None,None,None,3930166,0,None,None,None,NaN,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,NaN,None,None,None,None,None,None,1,Regular Play,None,NaN,None,1,Portugal,780,[4046659a-2a5c-496a-93a7-21c139e9fb8f],0,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,NaN,None,Portugal,780,00:00:00.000,Half Start,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,4046659a-2a5c-496a-93a7-21c139e9fb8f,4,None,None,None,3930166,0,None,None,None,NaN,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,NaN,None,None,None,None,None,None,1,Regular Play,None,NaN,None,1,Portugal,780,[4785617c-2983-4911-a9a6-9edd69fd948b],0,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,NaN,None,Czech Republic,912,00:00:00.000,Half Start,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
4,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,f38b626a-893f-4f74-93d4-a0d87f2534ff,1983,None,None,None,3930166,45,None,None,None,NaN,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,NaN,None,None,None,None,None,None,2,Regular Play,None,NaN,None,70,Czech Republic,912,[a8664822-bbe2-4a30-b9b5-2ef3154074ff],0,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,NaN,None,Portugal,780,00:00:00.000,Half Start,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2722388,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,0dd8fd49-5fea-4710-84fc-6e06fb83e757,3100,None,None,"[10.3, 32.8]",3930158,86,None,None,None,NaN,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,NaN,None,None,None,None,None,None,2,From Free Kick,Antonio Rüdiger,3167.0,Right Center Back,132,Scotland,942,[a291aa7d-39b0-4d7a-86f2-8be1171b7caf],32,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,NaN,None,Germany,770,00:41:32.702,Own Goal Against,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,"[29.752411154964918, 79.22086739213373, 0.0, 4...",False,False,False,"[17.191577570485677, 42.22972347817744]"
2722389,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,0dd8fd49-5fea-4710-84fc-6e06fb83e757,3100,None,None,"[10.3, 32.8]",3930158,86,None,None,None,NaN,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,NaN,None,None,None,None,None,None,2,From Free Kick,Antonio Rüdiger,3167.0,Right Center Back,132,Scotland,942,[a291aa7d-39b0-4d7a-86f2-8be1171b7caf],32,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,NaN,None,Germany,770,00:41:32.702,Own Goal Against,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,"[29.752411154964918, 79.22086739213373, 0.0, 4...",True,False,False,"[17.965696465999017, 29.694118095738418]"
2722390,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,0dd8fd49-5fea-4710-84fc-6e06fb83e757,3100,None,None,"[10.3, 32.8]",3930158,86,None,None,None,NaN,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,NaN,None,None,None,None,None,None,2,From Free Kick,Antonio Rüdiger,3167.0,Right Center Back,132,Scotland,942,[a291aa7d-39b0-4d7a-86f2-8be1171b7caf],32,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,NaN,None,Germany,770,00:41:32.702,Own Goal Against,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,"[29.752411154964918, 79.22086739213373, 0.0, 4...",True,False,False,"[25.70225726023301, 36.307377809078865]"
2722391,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,0dd8fd49-5fea-4710-84fc-6e06fb83e757,3100,None,None,"[10.3, 32.8]",3930158,86,None,None,None,NaN,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,NaN,None,None,None,None,None,None,2,From Free Kick,Antonio Rüdiger,3167.0,Right Center Back,132,Scotland,942,[a291aa7d-39b0-4d7a-86f2-8be1171b7caf],32,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,NaN,None,Germany,770,00:41:32.702,Own Goal Against,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,"[29.752411154964918, 79.22086739213373, 0.0, 4...",False,False,False,"[30.580730722937282, 47.8590938785301]"
2722392,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,0dd8fd49-5fea-4710-84fc-6e06fb83e757,3100,None,None,"[10.3, 32.8]",3930158,86,None,None,None,NaN,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,NaN,None,None,None,None,None,None,2,From Free Kick,Antonio Rüdiger,3167.0,Right Center Back,132,Scotland,942,[a291aa7d-39b0-4d7a-86f2-8be1171b7caf],32,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,NaN,None,Germany,770,00:41:32.702,Own Goal Against,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,"[29.752411154964918, 79.22086739213373, 0.0, 4...",True,False,False,"[37.21744231751122, 59.8941166423611]"

In [5]:
# manter apenas os atributos relevantes para a dimensão de competições
competitions = competitions[
    [
        "competition_id",
        "season_id",
        "country_name",
        "competition_name",
        "season_name"
    ]
]
# armazenar a tabela na camada de dados processados
competitions.to_parquet("../data/processed/competitions.parquet")
competitions

   competition_id  season_id country_name competition_name season_name
0              55        282       Europe        UEFA Euro        2024

In [6]:
# manter apenas os atributos relevantes para a dimensão de jogos
matches = matches[
    [
        "match_id",
        "match_date",
        "competition_id",
        "competition_name",
        "season_id",
        "season",
        "match_week",

        "home_team_id",
        "home_team",

        "away_team_id",
        "away_team",

        "home_score",
        "away_score",

        "competition_stage",

        "stadium",
    ]
]
matches

,match_id,match_date,competition_id,competition_name,season_id,season,match_week,home_team_id,home_team,away_team_id,away_team,home_score,away_score,competition_stage,stadium
0,3930166,2024-06-18,55,UEFA Euro,282,2024,1,780,Portugal,912,Czech Republic,2,1,Group Stage,Red Bull Arena
1,3930159,2024-06-15,55,UEFA Euro,282,2024,1,916,Hungary,773,Switzerland,1,3,Group Stage,RheinEnergieStadion
2,3930163,2024-06-16,55,UEFA Euro,282,2024,1,786,Serbia,768,England,0,1,Group Stage,VELTINS-Arena
3,3930181,2024-06-25,55,UEFA Euro,282,2024,3,768,England,944,Slovenia,0,0,Group Stage,RheinEnergieStadion
4,3930178,2024-06-24,55,UEFA Euro,282,2024,3,785,Croatia,914,Italy,1,1,Group Stage,Red Bull Arena
5,3930160,2024-06-15,55,UEFA Euro,282,2024,1,772,Spain,785,Croatia,3,0,Group Stage,Olympiastadion Berlin
6,3930170,2024-06-20,55,UEFA Euro,282,2024,2,944,Slovenia,786,Serbia,1,1,Group Stage,Allianz Arena
7,3938643,2024-06-25,55,UEFA Euro,282,2024,3,771,France,789,Poland,1,1,Group Stage,Signal-Iduna-Park
8,3938641,2024-06-21,55,UEFA Euro,282,2024,2,789,Poland,915,Austria,1,3,Group Stage,Olympiastadion Berlin
9,3938642,2024-06-22,55,UEFA Euro,282,2024,2,2138,Georgia,912,Czech Republic,1,1,Group Stage,Volksparkstadion
10,3938639,2024-06-18,55,UEFA Euro,282,2024,1,909,Turkey,2138,Georgia,3,1,Group Stage,Signal-Iduna-Park
11,3938638,2024-06-17,55,UEFA Euro,282,2024,1,905,Romania,911,Ukraine,3,0,Group Stage,Allianz Arena
12,3938640,2024-06-21,55,UEFA Euro,282,2024,2,908,Slovakia,911,Ukraine,1,2,Group Stage,Merkur Spiel-Arena
13,3938637,2024-06-16,55,UEFA Euro,282,2024,1,789,Poland,941,Netherlands,1,2,Group Stage,Volksparkstadion
14,3938644,2024-06-26,55,UEFA Euro,282,2024,3,2138,Georgia,780,Portugal,2,0,Group Stage,VELTINS-Arena
15,3941019,2024-07-01,55,UEFA Euro,282,2024,4,771,France,782,Belgium,1,0,Round of 16,Merkur Spiel-Arena
16,3942227,2024-07-06,55,UEFA Euro,282,2024,5,768,England,773,Switzerland,1,1,Quarter-finals,Merkur Spiel-Arena
17,3930174,2024-06-22,55,UEFA Euro,282,2024,2,909,Turkey,780,Portugal,0,3,Group Stage,Signal-Iduna-Park
18,3930162,2024-06-16,55,UEFA Euro,282,2024,1,944,Slovenia,776,Denmark,1,1,Group Stage,MHPArena
19,3930176,2024-06-23,55,UEFA Euro,282,2024,3,773,Switzerland,770,Germany,1,1,Group Stage,Deutsche Bank Park
20,3930169,2024-06-19,55,UEFA Euro,282,2024,2,942,Scotland,773,Switzerland,1,1,Group Stage,RheinEnergieStadion
21,3942819,2024-07-10,55,UEFA Euro,282,2024,6,941,Netherlands,768,England,1,2,Semi-finals,Signal-Iduna-Park
22,3943043,2024-07-14,55,UEFA Euro,282,2024,7,772,Spain,768,England,2,1,Final,Olympiastadion Berlin
23,3942752,2024-07-09,55,UEFA Euro,282,2024,6,772,Spain,771,France,2,1,Semi-finals,Allianz Arena
24,3942382,2024-07-06,55,UEFA Euro,282,2024,5,941,Netherlands,909,Turkey,2,1,Quarter-finals,Olympiastadion Berlin
25,3942349,2024-07-05,55,UEFA Euro,282,2024,5,780,Portugal,771,France,0,0,Quarter-finals,Volksparkstadion
26,3930180,2024-06-25,55,UEFA Euro,282,2024,3,941,Netherlands,915,Austria,2,3,Group Stage,Olympiastadion Berlin
27,3930171,2024-06-20,55,UEFA Euro,282,2024,2,776,Denmark,768,England,1,1,Group Stage,Deutsche Bank Park
28,3942226,2024-07-05,55,UEFA Euro,282,2024,5,772,Spain,770,Germany,2,1,Quarter-finals,MHPArena
29,3938645,2024-06-26,55,UEFA Euro,282,2024,3,911,Ukraine,782,Belgium,0,0,Group Stage,MHPArena
30,3930184,2024-06-26,55,UEFA Euro,282,2024,3,912,Czech Republic,909,Turkey,1,2,Group Stage,Volksparkstadion
31,3941022,2024-07-02,55,UEFA Euro,282,2024,4,915,Austria,909,Turkey,1,2,Round of 16,Red Bull Arena
32,3941021,2024-07-02,55,UEFA Euro,282,2024,4,905,Romania,941,Netherlands,0,3,Round of 16,Allianz Arena
33,3941020,2024-07-01,55,UEFA Euro,282,2024,4,780,Portugal,944,Slovenia,0,0,Round of 16,Deutsche Bank Park
34,3941018,2024-06-30,55,UEFA Euro,282,2024,4,772,Spain,2138,Georgia,4,1,Round of 16,RheinEnergieStadion
35,3941017,2024-06-30,55,UEFA Euro,282,2024,4,768,England,908,Slovakia,2,1,Round of 16,VELTINS-Arena
36,3930182,2024-06-25,55,UEFA Euro,282,2024,3,776,Denmark,786,Serbia,0,0,Group Stage,Allianz Arena
37,3930179,2024-06-24,55,UEFA Euro,282,2024,3,906,Albania,772,Spain,0,1,Group Stage,Merkur Spiel-Arena
38,3940983,2024-06-29,55,UEFA Euro,282,2024,4,770,Germany,776,Denmark,2,0,Round of 16,Signal-Iduna-Park
39,3940878,2024-06-29,55,UEFA Euro,282,2024,4,773,Switzerland,914,Italy,2,0,Round of 16,Olympiastadion Berlin
40,3930177,2024-06-23,55,UEFA Euro,282,2024,3,942,Scotland,916,Hungary,0,1,Group Stage,MHPArena
41,3930173,2024-06-21,55,UEFA Euro,282,2024,2,941,Netherlands,771,France,0,0,Group Stage,Trainingszentrum RB Leipzig Platz 1
42,3930172,2024-06-20,55,UEFA Euro,282,2024,2,772,Spain,914,Italy,1,0,Group Stage,VELTINS-Arena
43,3930167,2024-06-19,55,UEFA Euro,282,2024,2,785,Croatia,906,Albania,2,2,Group Stage,Volksparkstadion
44,3930168,2024-06-19,55,UEFA Euro,282,2024,2,770,Germany,916,Hungary,2,0,Group Stage,MHPArena
45,3930165,2024-06-17,55,UEFA Euro,282,2024,1,915,Austria,771,France,0,1,Group Stage,Merkur Spiel-Arena
46,3930164,2024-06-17,55,UEFA Euro,282,2024,1,782,Belgium,908,Slovakia,0,1,Group Stage,Deutsche Bank Park
47,3930161,2024-06-15,55,UEFA Euro,282,2024,1,914,Italy,906,Albania,2,1,Group Stage,Signal-Iduna-Park
48,3930183,2024-06-26,55,UEFA Euro,282,2024,3,908,Slovakia,905,Romania,1,1,Group Stage,Deutsche Bank Park
49,3930175,2024-06-22,55,UEFA Euro,282,2024,2,782,Belgium,905,Romania,2,0,Group Stage,RheinEnergieStadion
50,3930158,2024-06-14,55,UEFA Euro,282,2024,1,770,Germany,942,Scotland,5,1,Group Stage,Allianz Arena

In [7]:
# função para derivar a duração efetiva de cada período do jogo
# e suportar o cálculo posterior dos minutos jogados por jogador
def add_match_period_durations(matches, events_df):

    # obter o último minuto registado em cada período de cada jogo
    period_max = (
        events_df
        .groupby(["match_id", "period"], as_index=False)
        .agg(period_end_minute=("minute", "max"))
    )

    # pivotar os períodos
    period_wide = (
        period_max
        .pivot(index="match_id", columns="period", values="period_end_minute")
        .reset_index()
        .rename(columns={
            1: "first_half_end_minute",
            2: "second_half_end_minute",
            3: "extra_time_first_half_end_minute",
            4: "extra_time_second_half_end_minute",
        })
    )

    # excluir o período correspondente à disputa por penáltis por não contribuir para minutos jogados
    period_wide = period_wide.drop(columns=[5], errors="ignore")

    # identificar jogos com prolongamento a partir da existência do primeiro período extra
    period_wide["has_extra_time"] = (
        period_wide.get("extra_time_first_half_end_minute").notna()
        if "extra_time_first_half_end_minute" in period_wide.columns
        else False
    )

    minute_cols = [
        "first_half_end_minute",
        "second_half_end_minute",
        "extra_time_first_half_end_minute",
        "extra_time_second_half_end_minute",
    ]

    # manter apenas as colunas que existem no dataset, garantindo robustez entre competições
    existing_cols = [col for col in minute_cols if col in period_wide.columns]

    # calcular o minuto final do jogo com base no último período disponível
    period_wide["match_end_minute"] = period_wide[existing_cols].max(axis=1)

    # enriquecer a tabela de jogos com as durações derivadas dos eventos
    matches = matches.merge(period_wide, on="match_id", how="left")

    return matches

matches = add_match_period_durations(matches, events)

# armazenar a tabela na camada de dados processados
matches.to_parquet("../data/processed/matches.parquet")
matches

,match_id,match_date,competition_id,competition_name,season_id,season,match_week,home_team_id,home_team,away_team_id,away_team,home_score,away_score,competition_stage,stadium,first_half_end_minute,second_half_end_minute,extra_time_first_half_end_minute,extra_time_second_half_end_minute,has_extra_time,match_end_minute
0,3930166,2024-06-18,55,UEFA Euro,282,2024,1,780,Portugal,912,Czech Republic,2,1,Group Stage,Red Bull Arena,46.0,95.0,NaN,NaN,False,95.0
1,3930159,2024-06-15,55,UEFA Euro,282,2024,1,916,Hungary,773,Switzerland,1,3,Group Stage,RheinEnergieStadion,47.0,97.0,NaN,NaN,False,97.0
2,3930163,2024-06-16,55,UEFA Euro,282,2024,1,786,Serbia,768,England,0,1,Group Stage,VELTINS-Arena,47.0,94.0,NaN,NaN,False,94.0
3,3930181,2024-06-25,55,UEFA Euro,282,2024,3,768,England,944,Slovenia,0,0,Group Stage,RheinEnergieStadion,45.0,94.0,NaN,NaN,False,94.0
4,3930178,2024-06-24,55,UEFA Euro,282,2024,3,785,Croatia,914,Italy,1,1,Group Stage,Red Bull Arena,45.0,99.0,NaN,NaN,False,99.0
5,3930160,2024-06-15,55,UEFA Euro,282,2024,1,772,Spain,785,Croatia,3,0,Group Stage,Olympiastadion Berlin,47.0,95.0,NaN,NaN,False,95.0
6,3930170,2024-06-20,55,UEFA Euro,282,2024,2,944,Slovenia,786,Serbia,1,1,Group Stage,Allianz Arena,46.0,96.0,NaN,NaN,False,96.0
7,3938643,2024-06-25,55,UEFA Euro,282,2024,3,771,France,789,Poland,1,1,Group Stage,Signal-Iduna-Park,47.0,95.0,NaN,NaN,False,95.0
8,3938641,2024-06-21,55,UEFA Euro,282,2024,2,789,Poland,915,Austria,1,3,Group Stage,Olympiastadion Berlin,46.0,94.0,NaN,NaN,False,94.0
9,3938642,2024-06-22,55,UEFA Euro,282,2024,2,2138,Georgia,912,Czech Republic,1,1,Group Stage,Volksparkstadion,50.0,95.0,NaN,NaN,False,95.0
10,3938639,2024-06-18,55,UEFA Euro,282,2024,1,909,Turkey,2138,Georgia,3,1,Group Stage,Signal-Iduna-Park,46.0,97.0,NaN,NaN,False,97.0
11,3938638,2024-06-17,55,UEFA Euro,282,2024,1,905,Romania,911,Ukraine,3,0,Group Stage,Allianz Arena,47.0,94.0,NaN,NaN,False,94.0
12,3938640,2024-06-21,55,UEFA Euro,282,2024,2,908,Slovakia,911,Ukraine,1,2,Group Stage,Merkur Spiel-Arena,46.0,95.0,NaN,NaN,False,95.0
13,3938637,2024-06-16,55,UEFA Euro,282,2024,1,789,Poland,941,Netherlands,1,2,Group Stage,Volksparkstadion,46.0,95.0,NaN,NaN,False,95.0
14,3938644,2024-06-26,55,UEFA Euro,282,2024,3,2138,Georgia,780,Portugal,2,0,Group Stage,VELTINS-Arena,47.0,94.0,NaN,NaN,False,94.0
15,3941019,2024-07-01,55,UEFA Euro,282,2024,4,771,France,782,Belgium,1,0,Round of 16,Merkur Spiel-Arena,46.0,93.0,NaN,NaN,False,93.0
16,3942227,2024-07-06,55,UEFA Euro,282,2024,5,768,England,773,Switzerland,1,1,Quarter-finals,Merkur Spiel-Arena,45.0,92.0,105.0,121.0,True,121.0
17,3930174,2024-06-22,55,UEFA Euro,282,2024,2,909,Turkey,780,Portugal,0,3,Group Stage,Signal-Iduna-Park,45.0,95.0,NaN,NaN,False,95.0
18,3930162,2024-06-16,55,UEFA Euro,282,2024,1,944,Slovenia,776,Denmark,1,1,Group Stage,MHPArena,46.0,94.0,NaN,NaN,False,94.0
19,3930176,2024-06-23,55,UEFA Euro,282,2024,3,773,Switzerland,770,Germany,1,1,Group Stage,Deutsche Bank Park,46.0,94.0,NaN,NaN,False,94.0
20,3930169,2024-06-19,55,UEFA Euro,282,2024,2,942,Scotland,773,Switzerland,1,1,Group Stage,RheinEnergieStadion,48.0,94.0,NaN,NaN,False,94.0
21,3942819,2024-07-10,55,UEFA Euro,282,2024,6,941,Netherlands,768,England,1,2,Semi-finals,Signal-Iduna-Park,48.0,95.0,NaN,NaN,False,95.0
22,3943043,2024-07-14,55,UEFA Euro,282,2024,7,772,Spain,768,England,2,1,Final,Olympiastadion Berlin,47.0,94.0,NaN,NaN,False,94.0
23,3942752,2024-07-09,55,UEFA Euro,282,2024,6,772,Spain,771,France,2,1,Semi-finals,Allianz Arena,47.0,95.0,NaN,NaN,False,95.0
24,3942382,2024-07-06,55,UEFA Euro,282,2024,5,941,Netherlands,909,Turkey,2,1,Quarter-finals,Olympiastadion Berlin,47.0,96.0,NaN,NaN,False,96.0
25,3942349,2024-07-05,55,UEFA Euro,282,2024,5,780,Portugal,771,France,0,0,Quarter-finals,Volksparkstadion,45.0,93.0,105.0,120.0,True,120.0
26,3930180,2024-06-25,55,UEFA Euro,282,2024,3,941,Netherlands,915,Austria,2,3,Group Stage,Olympiastadion Berlin,47.0,97.0,NaN,NaN,False,97.0
27,3930171,2024-06-20,55,UEFA Euro,282,2024,2,776,Denmark,768,England,1,1,Group Stage,Deutsche Bank Park,46.0,93.0,NaN,NaN,False,93.0
28,3942226,2024-07-05,55,UEFA Euro,282,2024,5,772,Spain,770,Germany,2,1,Quarter-finals,MHPArena,47.0,94.0,106.0,126.0,True,126.0
29,3938645,2024-06-26,55,UEFA Euro,282,2024,3,911,Ukraine,782,Belgium,0,0,Group Stage,MHPArena,47.0,94.0,NaN,NaN,False,94.0
30,3930184,2024-06-26,55,UEFA Euro,282,2024,3,912,Czech Republic,909,Turkey,1,2,Group Stage,Volksparkstadion,48.0,97.0,NaN,NaN,False,97.0
31,3941022,2024-07-02,55,UEFA Euro,282,2024,4,915,Austria,909,Turkey,1,2,Round of 16,Red Bull Arena,46.0,95.0,NaN,NaN,False,95.0
32,3941021,2024-07-02,55,UEFA Euro,282,2024,4,905,Romania,941,Netherlands,0,3,Round of 16,Allianz Arena,48.0,94.0,NaN,NaN,False,94.0
33,3941020,2024-07-01,55,UEFA Euro,282,2024,4,780,Portugal,944,Slovenia,0,0,Round of 16,Deutsche Bank Park,47.0,94.0,105.0,120.0,True,120.0
34,3941018,2024-06-30,55,UEFA Euro,282,2024,4,772,Spain,2138,Georgia,4,1,Round of 16,RheinEnergieStadion,47.0,93.0,NaN,NaN,False,93.0
35,3941017,2024-06-30,55,UEFA Euro,282,2024,4,768,England,908,Slovakia,2,1,Round of 16,VELTINS-Arena,48.0,97.0,106.0,121.0,True,121.0
36,3930182,2024-06-25,55,UEFA Euro,282,2024,3,776,Denmark,786,Serbia,0,0,Group Stage,Allianz Arena,45.0,95.0,NaN,NaN,False,95.0
37,3930179,2024-06-24,55,UEFA Euro,282,2024,3,906,Albania,772,Spain,0,1,Group Stage,Merkur Spiel-Arena,45.0,94.0,NaN,NaN,False,94.0
38,3940983,2024-06-29,55,UEFA Euro,282,2024,4,770,Germany,776,Denmark,2,0,Round of 16,Signal-Iduna-Park,50.0,95.0,NaN,NaN,False,95.0
39,3940878,2024-06-29,55,UEFA Euro,282,2024,4,773,Switzerland,914,Italy,2,0,Round of 16,Olympiastadion Berlin,48.0,92.0,NaN,NaN,False,92.0
40,3930177,2024-06-23,55,UEFA Euro,282,2024,3,942,Scotland,916,Hungary,0,1,Group Stage,MHPArena,46.0,101.0,NaN,NaN,False,101.0
41,3930173,2024-06-21,55,UEFA Euro,282,2024,2,941,Netherlands,771,France,0,0,Group Stage,Trainingszentrum RB Leipzig Platz 1,46.0,95.0,NaN,NaN,False,95.0
42,3930172,2024-06-20,55,UEFA Euro,282,2024,2,772,Spain,914,Italy,1,0,Group Stage,VELTINS-Arena,47.0,96.0,NaN,NaN,False,96.0
43,3930167,2024-06-19,55,UEFA Euro,282,2024,2,785,Croatia,906,Albania,2,2,Group Stage,Volksparkstadion,46.0,98.0,NaN,NaN,False,98.0
44,3930168,2024-06-19,55,UEFA Euro,282,2024,2,770,Germany,916,Hungary,2,0,Group Stage,MHPArena,47.0,93.0,NaN,NaN,False,93.0
45,3930165,2024-06-17,55,UEFA Euro,282,2024,1,915,Austria,771,France,0,1,Group Stage,Merkur Spiel-Arena,46.0,99.0,NaN,NaN,False,99.0
46,3930164,2024-06-17,55,UEFA Euro,282,2024,1,782,Belgium,908,Slovakia,0,1,Group Stage,Deutsche Bank Park,47.0,98.0,NaN,NaN,False,98.0
47,3930161,2024-06-15,55,UEFA Euro,282,2024,1,914,Italy,906,Albania,2,1,Group Stage,Signal-Iduna-Park,48.0,95.0,NaN,NaN,False,95.0
48,3930183,2024-06-26,55,UEFA Euro,282,2024,3,908,Slovakia,905,Romania,1,1,Group Stage,Deutsche Bank Park,48.0,94.0,NaN,NaN,False,94.0
49,3930175,2024-06-22,55,UEFA Euro,282,2024,2,782,Belgium,905,Romania,2,0,Group Stage,RheinEnergieStadion,46.0,94.0,NaN,NaN,False,94.0
50,3930158,2024-06-14,55,UEFA Euro,282,2024,1,770,Germany,942,Scotland,5,1,Group Stage,Allianz Arena,48.0,93.0,NaN,NaN,False,93.0

Com o objetivo de suportar análises condicionadas pelo tempo de jogo, foi adicionada à tabela de lineups a métrica de minutos jogados por jogador em cada partida.

In [8]:
# converter valores temporais da StatsBomb para minutos
def time_to_minutes(value):
    if pd.isna(value) or value is None:
        return np.nan

    value = str(value)

    # tratar tempos no formato "minuto:segundo"
    if ":" in value:
        m, s = value.split(":")
        return int(m) + float(s) / 60

    return float(value)


# calcular os minutos restantes desde um determinado período até ao final do jogo
def minutes_from_period_to_end(start_minute, start_period, match_row):
    periods = []

    # construir lista de períodos disponíveis para o jogo
    if not pd.isna(match_row["first_half_end_minute"]):
        periods.append((1, 0, match_row["first_half_end_minute"]))
    if not pd.isna(match_row["second_half_end_minute"]):
        periods.append((2, 45, match_row["second_half_end_minute"]))
    if not pd.isna(match_row["extra_time_first_half_end_minute"]):
        periods.append((3, 90, match_row["extra_time_first_half_end_minute"]))
    if not pd.isna(match_row["extra_time_second_half_end_minute"]):
        periods.append((4, 105, match_row["extra_time_second_half_end_minute"]))

    total = 0.0
    start_period = int(start_period)

    # acumular apenas o tempo jogado a partir do período de entrada
    for i, (period_num, period_start, period_end) in enumerate(periods):
        if period_num < start_period:
            continue

        if period_num == start_period:
            total += period_end - start_minute
        else:
            prev_end = periods[i - 1][2]
            total += period_end - prev_end

    return total


# calcular os minutos jogados por jogador a partir da informação de lineups e substituições
def calculate_minutes_played(lineups_raw, matches):
    records = []

    for _, row in lineups_raw.iterrows():

        # obter informação posicional do jogador no jogo
        positions = row.get("positions", [])
        if not isinstance(positions, list) or len(positions) == 0:
            continue

        # considerar o primeiro intervalo de utilização registado para o jogador
        envelope = positions[0]

        start_minute = time_to_minutes(envelope.get("from"))
        start_period = envelope.get("from_period")
        end_reason = envelope.get("end_reason")
        end_raw = envelope.get("to")

        # assumir início do jogo quando o minuto de entrada não está preenchido
        if pd.isna(start_minute) or start_minute is None:
            start_minute = 0.0

        # obter dados temporais do jogo correspondente
        match_row = matches[matches["match_id"] == row["match_id"]].iloc[0]

        # se o jogador termina em campo, calcular minutos até ao apito final
        if end_reason == "Final Whistle" or end_raw is None:
            minutes = minutes_from_period_to_end(start_minute, start_period, match_row)

        # se o jogador sai antes do fim, calcular diferença direta entre saída e entrada
        else:
            end_minute = time_to_minutes(end_raw)
            minutes = max(0, end_minute - start_minute)

        records.append({
            "player_id": row["player_id"],
            "player_name": row["player_name"],
            "player_nickname": row["player_nickname"],
            "jersey_number": row["jersey_number"],
            "country": row["country"],
            "team_name": row["team_name"],
            "team_id": row["team_id"],
            "match_id": row["match_id"],
            "minutes_played": minutes,
        })

    return pd.DataFrame(records)


# garantir que a coluna positions está em formato lista antes do processamento
lineups["positions"] = lineups["positions"].apply(
    lambda x: x.tolist() if isinstance(x, np.ndarray) else x
)

# calcular minutos jogados e armazenar a tabela na camada de dados processados
lineups = calculate_minutes_played(lineups, matches)
lineups.to_parquet("../data/processed/lineups.parquet")

lineups

,player_id,player_name,player_nickname,jersey_number,country,team_name,team_id,match_id,minutes_played
0,3193,Bernardo Mota Veiga de Carvalho e Silva,Bernardo Silva,10,Portugal,Portugal,780,3930166,89.516667
1,5204,Bruno Miguel Borges Fernandes,Bruno Fernandes,8,Portugal,Portugal,780,3930166,95.000000
2,5206,Rúben Santos Gato Alves Dias,Rúben Dias,4,Portugal,Portugal,780,3930166,95.000000
3,5207,Cristiano Ronaldo dos Santos Aveiro,Cristiano Ronaldo,7,Portugal,Portugal,780,3930166,95.000000
4,6374,Nélson Cabral Semedo,Nélson Semedo,2,Portugal,Portugal,780,3930166,5.816667
...,...,...,...,...,...,...,...,...,...
1584,18797,Ryan Porteous,None,15,Scotland,Scotland,942,3930158,41.116667
1585,22308,Anthony Ralston,None,2,Scotland,Scotland,942,3930158,93.000000
1586,22379,Angus Gunn,None,1,Scotland,Scotland,942,3930158,93.000000
1587,31067,Billy Gilmour,None,14,Scotland,Scotland,942,3930158,26.566667
1588,38169,Lawrence Shankland,None,9,Scotland,Scotland,942,3930158,12.100000

Embora, num contexto profissional, seja recomendável preservar a totalidade das variáveis originais da tabela de eventos, uma vez que estas poderão vir a ser relevantes para o desenvolvimento de novas métricas ou análises futuras, neste projeto optou-se por armazenar na tabela de eventos processados apenas os atributos considerados necessários para as métricas e análises implementadas. Esta decisão permite reduzir redundância, simplificar o modelo de dados e tornar a base de dados mais eficiente e orientada ao caso de uso analítico definido.

In [9]:
# Colunas necessárias para o cálculo das métricas
METRICS_COLS = [
    # Identificação do evento
    "id", "index", "match_id", "period", "minute", "second", "timestamp",
    "possession", "possession_team", "possession_team_id",
    "type", "play_pattern",

    # Flags de contexto do freeze frame
    "actor", "teammate", "keeper",

    # Coordenadas
    "location_x", "location_y",

    # Info do jogador/equipa
    "player", "player_id", "team", "team_id", "position",

    # Atributos do passe
    "pass_end_location",
    "pass_length", "pass_angle",
    "pass_height", "pass_body_part",
    "pass_type", "pass_outcome",
    "pass_cross",
    "pass_recipient", "pass_recipient_id",
    "pass_shot_assist", "pass_goal_assist",
    "pass_assisted_shot_id",
    "pass_switch", "pass_through_ball",
    "pass_technique",

    # Atributos do remate (para o outcome window)
    "shot_statsbomb_xg", "shot_outcome",

]

# Manter apenas essas colunas
cols_to_keep = [c for c in METRICS_COLS if c in events.columns]
events = events[cols_to_keep].copy()


# armazenar a tabela na camada de dados processados
events.to_parquet("../data/processed/events.parquet")
events

,id,index,match_id,period,minute,second,timestamp,possession,possession_team,possession_team_id,type,play_pattern,actor,teammate,keeper,location_x,location_y,player,player_id,team,team_id,position,pass_end_location,pass_length,pass_angle,pass_height,pass_body_part,pass_type,pass_outcome,pass_cross,pass_recipient,pass_recipient_id,pass_shot_assist,pass_goal_assist,pass_assisted_shot_id,pass_switch,pass_through_ball,pass_technique,shot_statsbomb_xg,shot_outcome
0,9d27853c-ffbc-4011-b7eb-fe3d438e8376,1,3930166,1,0,0,00:00:00.000,1,Portugal,780,Starting XI,Regular Play,None,None,None,None,None,None,NaN,Portugal,780,None,None,NaN,NaN,None,None,None,None,None,None,NaN,None,None,None,None,None,None,NaN,None
1,39ad76b2-caaa-41e0-8eb5-f42de9e4e2c6,2,3930166,1,0,0,00:00:00.000,1,Portugal,780,Starting XI,Regular Play,None,None,None,None,None,None,NaN,Czech Republic,912,None,None,NaN,NaN,None,None,None,None,None,None,NaN,None,None,None,None,None,None,NaN,None
2,4785617c-2983-4911-a9a6-9edd69fd948b,3,3930166,1,0,0,00:00:00.000,1,Portugal,780,Half Start,Regular Play,None,None,None,None,None,None,NaN,Portugal,780,None,None,NaN,NaN,None,None,None,None,None,None,NaN,None,None,None,None,None,None,NaN,None
3,4046659a-2a5c-496a-93a7-21c139e9fb8f,4,3930166,1,0,0,00:00:00.000,1,Portugal,780,Half Start,Regular Play,None,None,None,None,None,None,NaN,Czech Republic,912,None,None,NaN,NaN,None,None,None,None,None,None,NaN,None,None,None,None,None,None,NaN,None
4,f38b626a-893f-4f74-93d4-a0d87f2534ff,1983,3930166,2,45,0,00:00:00.000,70,Czech Republic,912,Half Start,Regular Play,None,None,None,None,None,None,NaN,Portugal,780,None,None,NaN,NaN,None,None,None,None,None,None,NaN,None,None,None,None,None,None,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2722388,0dd8fd49-5fea-4710-84fc-6e06fb83e757,3100,3930158,2,86,32,00:41:32.702,132,Scotland,942,Own Goal Against,From Free Kick,False,False,False,"[10.3, 32.8]","[17.191577570485677, 42.22972347817744]",Antonio Rüdiger,3167.0,Germany,770,Right Center Back,None,NaN,NaN,None,None,None,None,None,None,NaN,None,None,None,None,None,None,NaN,None
2722389,0dd8fd49-5fea-4710-84fc-6e06fb83e757,3100,3930158,2,86,32,00:41:32.702,132,Scotland,942,Own Goal Against,From Free Kick,False,True,False,"[10.3, 32.8]","[17.965696465999017, 29.694118095738418]",Antonio Rüdiger,3167.0,Germany,770,Right Center Back,None,NaN,NaN,None,None,None,None,None,None,NaN,None,None,None,None,None,None,NaN,None
2722390,0dd8fd49-5fea-4710-84fc-6e06fb83e757,3100,3930158,2,86,32,00:41:32.702,132,Scotland,942,Own Goal Against,From Free Kick,False,True,False,"[10.3, 32.8]","[25.70225726023301, 36.307377809078865]",Antonio Rüdiger,3167.0,Germany,770,Right Center Back,None,NaN,NaN,None,None,None,None,None,None,NaN,None,None,None,None,None,None,NaN,None
2722391,0dd8fd49-5fea-4710-84fc-6e06fb83e757,3100,3930158,2,86,32,00:41:32.702,132,Scotland,942,Own Goal Against,From Free Kick,False,False,False,"[10.3, 32.8]","[30.580730722937282, 47.8590938785301]",Antonio Rüdiger,3167.0,Germany,770,Right Center Back,None,NaN,NaN,None,None,None,None,None,None,NaN,None,None,None,None,None,None,NaN,None
2722392,0dd8fd49-5fea-4710-84fc-6e06fb83e757,3100,3930158,2,86,32,00:41:32.702,132,Scotland,942,Own Goal Against,From Free Kick,False,True,False,"[10.3, 32.8]","[37.21744231751122, 59.8941166423611]",Antonio Rüdiger,3167.0,Germany,770,Right Center Back,None,NaN,NaN,None,None,None,None,None,None,NaN,None,None,None,None,None,None,NaN,None

# Métrica Line-Breaking Pass Value

A métrica **Line-Breaking Pass Value (LBPV)** procura quantificar o valor contextual de passes que conseguem penetrar estruturas defensivas adversárias. Em vez de medir apenas o número de passes progressivos ou o número de linhas quebradas, a métrica avalia a capacidade de um passe gerar vantagem posicional e desorganizar o bloco defensivo através da combinação entre progressão no terreno de jogo, linhas defensivas quebradas, número de adversários ultrapassados e consequência ofensiva da ação.

## Definição

Um **passe que quebra linhas** é um passe rasteiro ou baixo que penetra fisicamente um bloco defensivo e permite avançar a bola de forma significativa no terreno de jogo. Os filtros iniciais aplicados foram os seguintes:

- Apenas passes com `pass_height` igual a `"Ground Pass"` ou `"Low Pass"`
- Apenas passes concluídos com sucesso
- Exclusão de bolas paradas e cruzamentos
- Exclusão de passes realizados por guarda-redes


## Critérios Geométricos

Para que um passe seja classificado como line-breaking, tem de satisfazer **todas** 
as seguintes condições de forma simultânea:

### 1. Avanço mínimo — o passe tem de ganhar terreno (progressivo)

O passe tem de avançar pelo menos **12 metros no eixo X** (direção de ataque), 
o equivalente a 10% do comprimento total do campo StatsBomb (120m).


<div align="center">

`distance_advanced = end_x − pass_x ≥ 12m`

</div>


### 2. Linha defensiva no trajeto do passe

Deve existir no mínimo uma linha defensiva **entre o passador e o destino do passe**.

### Como são identificadas as linhas defensivas

As linhas são detectadas automaticamente a partir do **freeze frame** do 
StatsBomb 360.

Filtra-se para os adversários (excluindo guarda-redes) e agrupa-se por 
proximidade em X usando **clustering por gaps**:

> Se dois defesas consecutivos (ordenados por X) estiverem a **mais de 4,5m** 
> de distância entre si, pertencem a linhas defensivas diferentes.

Apenas grupos com **2 ou mais defesas** são considerados uma linha. 
Jogadores isolados não formam uma linha e são ignorados na deteção.

Para cada linha, calcula-se a posição média em X dos defesas que a formam 
(`line_x`). Essa posição tem de estar contida no intervalo:

<div align="center">

`pass_x ≤ line_x ≤ end_x`

</div>


### 3. O passe tem de passar entre dois defesas
Não basta o passe avançar além de uma linha, este tem de passar **pelo espaço entre 
dois defesas adjacentes** dessa linha.
Para isso, calcula-se onde a trajetória do passe está em `line_x` 
(interpolação linear) e verifica-se se esse ponto Y cai entre dois defesas 
consecutivos ordenados por Y:

<div align="center">

`y_defesa_i ≤ y_trajeto ≤ y_defesa_i+1`

</div>

Esta restrição foi introduzida para evitar que passes que contornam a linha defensiva pela largura (por fora do último defesa) sejam classificados como line-breaking, uma vez que essas ações exploram espaço lateral em vez de romper diretamente a estrutura defensiva adversária.


### 4. Distância mínima ao ponto de cruzamento

A distância Euclidiana entre o passador e o ponto onde a trajetória do passe cruza a 
linha defensiva tem de ser **≥ 5 metros**:

<div align="center">

`√((line_x − pass_x)² + (y_crossing − pass_y)²) ≥ 5m`

</div>


Esta condição evita falsos positivos em situações onde o passador está já 
encostado à linha, e um passe parece geometricamente 
"romper" a linha quando na prática não há qualquer disrupção tática.

## Metric Score

O score final da métrica é calculado através de uma combinação ponderada de diferentes componentes contextuais associadas ao passe. Cada componente é normalizada para o intervalo `[0,1]`, permitindo comparar ações com características distintas numa escala comum.

<div align="center">

`score = Σ (peso × componente_normalizada)`

</div>

| Componente | Peso | O que representa |
|---|---:|---|
| `zone_value` | 10% | Valor posicional da zona onde o passe tem origem |
| `distance_norm` | 15% | Capacidade de progressão territorial do passe |
| `defenders_norm` | 30% | Número de adversários ultrapassados entre origem e destino |
| `line_break_norm` | 20% | Número de linhas defensivas efetivamente quebradas |
| `outcome_norm` | 25% | Consequência ofensiva gerada após o passe |

#### `zone_value`
Mede o valor posicional da origem do passe através de uma função sigmoide baseada na coordenada `x` do passe. A função atribui maior valor a passes iniciados em zonas mais avançadas do terreno, com crescimento mais acentuado a partir de zonas intermédias/ofensivas.

#### `distance_norm`
Representa a progressão territorial do passe no eixo X, calculada através de `end_x - pass_x`. A variável é normalizada relativamente ao maior valor observado nos passes identificados como line-breaking.

#### `defenders_norm`
Quantifica o número de adversários cuja coordenada X se encontra estritamente entre a origem e o destino do passe. Funciona como aproximação ao número de jogadores ultrapassados pela ação. O valor é normalizado relativamente ao máximo observado no conjunto de passes identificados.

#### `line_break_norm`
Representa o número de linhas defensivas quebradas pelo passe. O valor é normalizado dividindo o número de linhas quebradas por `3`, com limite máximo de `1.0`.

#### `outcome_norm`
Avalia a consequência ofensiva da ação através de remates gerados nos `10` segundos seguintes dentro da mesma posse. Quando o passe é identificado como assistência direta para remate ou golo (`pass_shot_assist = True` ou `pass_goal_assist = True`), recebe crédito total do xG da finalização. Caso exista remate dentro da janela temporal mas sem assistência direta identificada, o valor é penalizado por um fator de `0.6`, representando uma contribuição ofensiva indireta. Se o remate resultar em golo, o valor base é `1.0`, também ajustado pelo mesmo critério de diretividade.

A soma dos pesos é igual a `1.0`, pelo que o score final fica naturalmente limitado ao intervalo `[0,1]`.

## Limitações

**Freeze frames estáticos** — A deteção de linhas defensivas é baseada exclusivamente no freeze frame disponibilizado pelo StatsBomb 360 no instante do passe. Como apenas existe uma fotografia estática do momento, não é possível observar a movimentação contínua dos jogadores e da bola durante a trajetória do passe. Além disso, apenas os jogadores capturados no freeze frame estão disponíveis para análise, podendo existir adversários fora da área observada que influenciem a estrutura defensiva real. Com dados completos de tracking seria possível modelar de forma significativamente mais rigorosa a interação entre a trajetória da bola e o bloco defensivo, verificando em tempo real se o passe atravessou efetivamente uma linha defensiva.

**Deteção aproximada de linhas defensivas** — As linhas são inferidas através de clustering baseado apenas na coordenada X dos adversários. Embora esta abordagem permita identificar estruturas defensivas de forma simples e interpretável linhas muito compactas ou posicionamentos diagonais podem originar agrupamentos imperfeitos.

**Normalização dependente do dataset** — As componentes `distance_norm` e `defenders_norm` são normalizadas relativamente aos valores máximos presentes no dataset analisado. Como consequência, os scores devem ser interpretados sobretudo de forma contextual dentro do mesmo ambiente competitivo, sendo menos adequados para comparação direta entre competições, épocas ou datasets distintos.

In [10]:
# VARIÁVEIS CONSTANTES
PITCH_LENGTH = 120.0
PITCH_WIDTH  = 80.0

MIN_ADVANCE_X      = 12.0   # avanço mínimo de 10% do comprimento do campo (120m)
LINE_GAP_THRESHOLD = 4.5    # gap em X > 4.5m → nova linha defensiva
MIN_LINE_SIZE      = 2      # uma linha necessita de pelo menos 2 defesas
OUTCOME_WINDOW_SEC = 10.0   # segundos para procurar remate/golo após o passe
SHOT_ASSIST_FACTOR = 0.6    # multiplicador para remates sem assistência direta
MIN_START_DIST = 5.0        # o passador deve estar a pelo menos 5m do ponto de interseção

# Pesos das componentes do score
WEIGHTS = {
    "zone":        0.10,
    "distance":    0.15,
    "defenders":   0.30,
    "line_break":  0.20,
    "outcome":     0.25,
}

In [11]:
# HELPERS
import os
import sys
sys.path.insert(0, os.path.abspath("../"))

from utils.utils import (
    _extract_xy,
    _zone_value,
    _timestamp_to_seconds,
    _cluster_defenders_into_lines,
    _pass_y_at_x,
    _count_lines_broken,
    _count_defenders_bypassed,
)

/Users/goncalo.rodrigues9/.matplotlib is not a writable directory
Matplotlib created a temporary cache directory at /var/folders/21/7hv4zdjs1xg_628k1767wlpc0000gn/T/matplotlib-zx3njk29 because there was an issue with the default path (/Users/goncalo.rodrigues9/.matplotlib); it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib is building the font cache; this may take a moment.

In [12]:
# main pipeline da métrica Line-Breaking Pass Value (LBPV)
def compute_line_breaking_passes(events: pd.DataFrame) -> pd.DataFrame:
    
    # filtrar passes progressivos e excluir guarda redes
    passes_actor = events[
        (events["type"] == "Pass") &
        (events["actor"] == True) &
        (~events["keeper"].eq(True))
    ].copy()

    # excluir bolas paradas
    setpiece_types = {"Corner", "Free Kick", "Throw-in", "Kick Off"}
    if "pass_type" in passes_actor.columns:
        passes_actor = passes_actor[
            ~passes_actor["pass_type"].isin(setpiece_types)
        ]

    # excluis passes incompletos
    non_complete = {"Incomplete", "Out", "Pass Offside", "Unknown", "Injury Clearance"}
    if "pass_outcome" in passes_actor.columns:
        passes_actor = passes_actor[
            ~passes_actor["pass_outcome"].isin(non_complete)
        ]

    # excluir cruzamentos
    if "pass_cross" in passes_actor.columns:
        passes_actor = passes_actor[
            passes_actor["pass_cross"].isna()
        ]

    # Apenas incluir passes rasteiros ou baixos
    if "pass_height" in passes_actor.columns:
        passes_actor = passes_actor[
            passes_actor["pass_height"].isin({"Ground Pass", "Low Pass"})
        ]

    # extrair coordenadas de evento
    passes_actor[["pass_x", "pass_y"]] = passes_actor["location_x"].apply(
        lambda v: pd.Series(_extract_xy(v))
    )

    # extrair coordenadas de destino do passe
    passes_actor[["end_x", "end_y"]] = passes_actor["pass_end_location"].apply(
        lambda v: pd.Series(_extract_xy(v))
    )

    # remove passes com coordenadas inválidas
    passes_actor = passes_actor.dropna(subset=["pass_x", "end_x"])

    # calcular progressão do passe no eixo X e filtrar passes progressivos
    passes_actor["distance_advanced"] = passes_actor["end_x"] - passes_actor["pass_x"]
    progressive = passes_actor[
        passes_actor["distance_advanced"] >= MIN_ADVANCE_X
    ].copy()

    # extrair linhas dos adversários presentes no freeze frame
    defenders_df = events[
        (events["type"] == "Pass") &
        (events["teammate"] == False) &
        (events["actor"] == False) &
        (~events["keeper"].eq(True))
    ][["id", "location_y"]].copy()

    # extrair coordenadas (x, y) dos adversários
    defenders_df[["def_x", "def_y"]] = defenders_df["location_y"].apply(
        lambda v: pd.Series(_extract_xy(v))
    )

    # remover adversários sem coordenadas válidas
    defenders_df = defenders_df.dropna(subset=["def_x", "def_y"])

    # agrupar coordenadas dos adversários por evento
    def_positions = (
        defenders_df
        .groupby("id")
        .apply(lambda g: list(zip(g["def_x"], g["def_y"])))
        .reset_index()
        .rename(columns={0: "defenders_xy"})
    )

    # juntar df de passes progressivos com o posicionamento dos adversários por evento
    progressive = progressive.merge(def_positions, on="id", how="left")

    # substituir valores ausentes por listas vazias
    progressive["defenders_xy"] = progressive["defenders_xy"].apply(
        lambda v: v if isinstance(v, list) else []
    )

    # calcular número de linhas quebradas e defesas ultrapassados
    results = progressive.apply(
        lambda row: pd.Series({
            "lines_broken": _count_lines_broken(
                row["pass_x"], row["pass_y"],
                row["end_x"], row["end_y"],
                row["defenders_xy"]
            ),
            "n_defenders_bypassed": _count_defenders_bypassed(
                row["pass_x"], row["end_x"],
                row["defenders_xy"]
            ),
        }),
        axis=1
    )
    progressive = pd.concat([progressive, results], axis=1)

    # filtrar os passes que quebram uma ou mais linhas
    line_breakers = progressive[progressive["lines_broken"] >= 1].copy()

    # calcular timestamps em segundos para os eventos relevantes (verificar outcome nos 10s seguintes)
    all_ts = events[[
        "id", "match_id", "possession", "type",
        "timestamp", "shot_statsbomb_xg", "shot_outcome", "actor"
    ]].copy()

    # manter apenas uma linha por evento, correspondente ao jogador que realizou a ação
    all_ts = all_ts[all_ts["actor"] == True]

    # remover coluna auxiliar depois da filtragem
    all_ts = all_ts.drop(columns=["actor"])

    # converter timestamp para segundos, facilitando o cálculo da janela temporal
    all_ts["ts_sec"] = all_ts["timestamp"].apply(_timestamp_to_seconds)

    # criar dicionário com os remates por jogo e posse
    # chave: (match_id, possession)
    # valor: lista de tuplos (timestamp do remate, xG, outcome do remate)
    shots_lookup = (
        all_ts[all_ts["type"] == "Shot"]
        .groupby(["match_id", "possession"])
        .apply(lambda g: list(zip(
            g["ts_sec"],
            g["shot_statsbomb_xg"],
            g["shot_outcome"]
        )))
        .to_dict()
    )

    # juntar timestamp do passe aos passes line-breaking
    line_breakers = line_breakers.merge(
        all_ts[["id", "ts_sec"]].rename(columns={"ts_sec": "pass_ts_sec"}),
        on="id",
        how="left"
    )

    # calcular valor ofensivo gerado após cada passe
    def _get_outcome(row):

        # identificar jogo e posse do passe
        key = (row["match_id"], row["possession"])

        # obter remates dessa posse
        shots = shots_lookup.get(key, [])

        # timestamp do passe em segundos
        pass_ts = row.get("pass_ts_sec", np.nan)

        # se o passe não tiver timestamp válido, não recebe crédito ofensivo
        if np.isnan(pass_ts):
            return 0.0

        # verificar se o passe foi assistência direta para remate ou golo
        is_direct = bool(
            row.get("pass_shot_assist", False) or
            row.get("pass_goal_assist", False)
        )

        # procurar remates dentro da janela temporal definida após o passe
        for shot_ts, xg, outcome_name in shots:

            if 0 <= (shot_ts - pass_ts) <= OUTCOME_WINDOW_SEC:

                # se o remate for golo, atribuir valor máximo
                # caso não seja assistência direta, aplicar penalização
                if str(outcome_name) == "Goal":
                    return 1.0 if is_direct else 1.0 * SHOT_ASSIST_FACTOR

                # obter valor de xG; se estiver ausente, usar valor residual por defeito
                xg_val = float(xg) if xg is not None and not (
                    isinstance(xg, float) and np.isnan(xg)
                ) else 0.05

                # assistência direta recebe xG completo; contribuição indireta recebe xG penalizado
                return xg_val if is_direct else xg_val * SHOT_ASSIST_FACTOR

        # sem remate na janela temporal, não há crédito ofensivo
        return 0.0

    # aplicar cálculo de outcome ofensivo a cada passe line-breaking
    line_breakers["outcome_value"] = line_breakers.apply(_get_outcome, axis=1)

    # calcular valor posicional da origem do passe
    line_breakers["zone_value"] = line_breakers["pass_x"].apply(_zone_value)

    # normalizar progressão do passe pelo máximo observado no dataset
    max_dist = line_breakers["distance_advanced"].max()
    line_breakers["distance_norm"] = (
        line_breakers["distance_advanced"] / max(max_dist, 1.0)
    )

    # normalizar número de adversários ultrapassados pelo máximo observado no dataset
    max_def = line_breakers["n_defenders_bypassed"].max()
    line_breakers["defenders_norm"] = (
        line_breakers["n_defenders_bypassed"] / max(max_def, 1.0)
    )

    # normalizar linhas quebradas, assumindo 3 linhas como referência máxima razoável
    line_breakers["line_break_norm"] = (
        line_breakers["lines_broken"] / 3.0
    ).clip(upper=1.0)

    # limitar outcome ofensivo ao intervalo [0, 1]
    line_breakers["outcome_norm"] = line_breakers["outcome_value"].clip(upper=1.0)

    # calcular score composto ponderado
    line_breakers["score"] = (
        WEIGHTS["zone"]       * line_breakers["zone_value"] +
        WEIGHTS["distance"]   * line_breakers["distance_norm"] +
        WEIGHTS["defenders"]  * line_breakers["defenders_norm"] +
        WEIGHTS["line_break"] * line_breakers["line_break_norm"] +
        WEIGHTS["outcome"]    * line_breakers["outcome_norm"]
    )

    # selecionar colunas finais a devolver no output
    output_cols = [
        "id", "match_id", "player", "player_id", "team", "team_id",
        "period", "minute", "second", "timestamp",
        "pass_x", "pass_y", "end_x", "end_y",
        "pass_length", "pass_angle",
        "distance_advanced",
        "n_defenders_bypassed", "lines_broken",
        "zone_value", "distance_norm", "defenders_norm",
        "line_break_norm", "outcome_value", "outcome_norm",
        "score_raw", "score",
        "pass_outcome", "pass_body_part", "pass_recipient"
    ]

    # manter apenas colunas existentes no DataFrame
    output_cols = [c for c in output_cols if c in line_breakers.columns]

    # criar DataFrame final da métrica
    result = line_breakers[output_cols].copy()

    return result

In [13]:
# calcular métrica Line-Breaking Pass Value
line_breaking_passes = compute_line_breaking_passes(events)

# armazenar a tabela na camada de dados processados
line_breaking_passes.to_parquet("../data/processed/line_breaking_passes.parquet", index=False)
line_breaking_passes

,id,match_id,player,player_id,team,team_id,period,minute,second,timestamp,pass_x,pass_y,end_x,end_y,pass_length,pass_angle,distance_advanced,n_defenders_bypassed,lines_broken,zone_value,distance_norm,defenders_norm,line_break_norm,outcome_value,outcome_norm,score,pass_outcome,pass_body_part,pass_recipient
0,9c1d1a0e-6e18-4edb-9fdf-a0a8342b7fc4,3930166,Bruno Miguel Borges Fernandes,5204.0,Portugal,780,1,2,13,00:02:13.104,84.9,18.5,102.4,27.9,19.864794,0.492919,17.5,7,2,0.767099,0.308642,0.7,0.666667,0.0,0.0,0.466339,None,Right Foot,Bernardo Mota Veiga de Carvalho e Silva
1,d3c3d565-0aa5-4dcd-bf46-52d700ed484c,3930166,Bruno Miguel Borges Fernandes,5204.0,Portugal,780,1,2,51,00:02:51.819,37.9,62.5,50.9,20.1,44.348167,-1.273292,13.0,3,1,0.071226,0.229277,0.3,0.333333,0.0,0.0,0.198181,None,Right Foot,João Pedro Cavaco Cancelo
2,5121ac5f-700a-406b-9d89-3d35ad1bfb90,3930166,Tomáš Souček,4870.0,Czech Republic,912,1,6,39,00:06:39.061,66.1,39.3,80.4,24.7,20.436487,-0.795778,14.3,4,1,0.422627,0.252205,0.4,0.333333,0.0,0.0,0.266760,None,Right Foot,Pavel Šulc
3,bdb32880-0a32-4473-b6c1-202928b12bbf,3930166,Nuno Mendes,41092.0,Portugal,780,1,9,32,00:09:32.046,70.7,9.7,82.8,11.1,12.180722,0.115190,12.1,5,1,0.513996,0.213404,0.5,0.333333,0.0,0.0,0.300077,None,Left Foot,Cristiano Ronaldo dos Santos Aveiro
4,d6fec69b-b5c1-4818-8566-46b0f1187f10,3930166,Tomáš Holeš,16469.0,Czech Republic,912,1,9,50,00:09:50.244,31.7,61.9,51.1,62.7,19.416489,0.041214,19.4,4,1,0.044617,0.342152,0.4,0.333333,0.0,0.0,0.242451,None,Right Foot,Jan Kuchta
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1187,6570ac3b-3174-4d79-a3c0-7cc2f75bbaea,3930158,Ryan Porteous,18797.0,Scotland,942,1,23,5,00:23:05.255,14.6,66.9,43.1,63.8,28.668100,-0.108346,28.5,4,1,0.011751,0.502646,0.4,0.333333,0.0,0.0,0.263239,None,Right Foot,John McGinn
1188,81c25f23-fd1e-44b7-b760-42eff4c79426,3930158,Andrew Robertson,3655.0,Scotland,942,1,47,14,00:47:14.868,64.0,3.1,82.2,8.6,19.012890,0.293472,18.2,5,1,0.382252,0.320988,0.5,0.333333,0.0,0.0,0.303040,None,Left Foot,Che Adams
1189,98fddc5a-5434-413e-97c4-f340cebfb28f,3930158,Antonio Rüdiger,3167.0,Germany,770,2,59,10,00:14:10.187,77.8,55.6,92.8,53.4,15.160475,-0.145628,15.0,4,1,0.651128,0.264550,0.4,0.333333,0.0,0.0,0.291462,None,Right Foot,Kai Havertz
1190,2db1e087-be16-4b8f-9908-b2caa68f9f8b,3930158,Kieran Tierney,10540.0,Scotland,942,2,61,24,00:16:24.858,28.3,10.0,44.6,12.8,16.538742,0.170119,16.3,2,1,0.034357,0.287478,0.2,0.333333,0.0,0.0,0.173224,None,Left Foot,John McGinn
1191,54396841-71e4-48f5-92bb-91011bea1f8e,3930158,Maximilian Mittelstädt,12407.0,Germany,770,2,71,22,00:26:22.749,63.6,19.2,76.5,30.6,17.215400,0.723748,12.9,6,1,0.374725,0.227513,0.6,0.333333,0.0,0.0,0.318266,None,Left Foot,İlkay Gündoğan